# This config will be used for tests

database_url = "postgres://postgres:postgres@localhost/canana"
jwt_secret = "secretsecretsecret"
sentry_dsn = ""
internal_key = ""

[urls]
verify_link = "http://localhost:5173/auth/verify?t="
email_tfa_link = "http://localhost:5173/auth/tfa?t="
recovery_link = "http://localhost:5173/auth/recovery?t="
cancel_email_change_link = "http://localhost:5173/auth/cancel-email-change?t="
image_proxy_link = "http://localhost:5173/image/"
payment_success = "http://localhost:5173/market/payments/success"
payment_failure = "http://localhost:5173/market/payments/failure"
payment_webhook = "http://localhost:8000/payments/hook/"

[ports]
auth = 31001
email = 31002
images = 31003
level = 31004

[email]
host = "unused"
username = "me@bonfire.moe"
password = "unused"
# emails are not sent from dummy@*.* addresses
from = "Canana <dummy@bonfire.moe>"

[images]
type = "local"
root = "./images"

[clearance]
enabled = false
